# Quiz Configuration
# Created by Harrison#4651 <https://harriiison.me>

# EXAMPLE
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# HOW TO USE:
#
# quizName is the name of the quiz (one word)
# under the quiz name you must include a numbered list of all the questions
# under the answers you must also include a numbered list of all the answers
# the outcomes is a list of final options that the answer contributes towards
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# quizName:
#   1:
#     question: "The First Question"
#     answers:
#       1:
#         answer: "The First Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"
#       2:
#         answer: "The Second Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"
#       3:
#         answer: "The Third Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"
#   2:
#     question: "The Second Question"
#     answers:
#       1:
#         answer: "The First Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"
#       2:
#         answer: "The Second Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"
#       3:
#         answer: "The Third Answer"
#         outcomes:
#            - "Option1"
#            - "Option2"

# SETTINGS
#
# These settings are customisable for each quiz.
# Simply enter the name of the quiz and copy each of the settings as shown below:
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# HOW TO USE
#
# questionTitle is the text in the title shown on the player's screen before each question
# questionSubtitle is the text in the subtitle shown on the player's screen before each question
# questionFormat is the format of the question message
# answerFormat is the format of the answer message
# endMessage is the format of the quiz completion message
# outcomeMessage is the format of the message telling you your result
# * Colour codes are supported *
#
# The following placeholders can be used: (include curly brackets)
# - {quizName} --> the name of the quiz
# - {questionNo} --> the question number
# - {question} --> the question
# - {answerNo} --> the answer number
# - {answer} --> the answer
# - {outcome} --> the quiz outcome
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# quizName:
#   questionTitle: "&eQuestion {questionNo}"
#   questionSubtitle: "&7Click the corresponding option in chat to answer"
#   questionFormat: "&bQuestion {questionNo}: &e{question}"
#   answerFormat: "&b[{answerNo}] &3{answer}"
#   endMessage: "&c&lThe quiz is over!"
#   outcomeMessage: "&bBased on your answers you are best fit to have &e{outcome} &bas your Godly Parent"
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

# QUIZ SETTINGS

settings:
  exampleQuiz:
    questionTitle: "&eQuestion {questionNo}"
    questionSubtitle: "&7Click the corresponding option in chat to answer"
    questionFormat: "&bQuestion {questionNo}: &e{question}"
    answerFormat: "&b[{answerNo}] &3{answer}"
    endMessage: "&c&lThe quiz is over!"
    outcomeMessage: "&bYour most commonly selected answer was &e{outcome}"

# YOUR QUIZZES:

# This operational example is a quiz that finds who your ideal Greek God parent would be based on your answers.
# To create your own simple change "exampleQuiz" to your quiz name,
# and modify the questions, answers and outcomes respectively.
exampleQuiz:
  1:
    question: "What is your favourite animal?"
    answers:
      1:
        answer: "Eagle"
        outcomes:
          - "Zeus"
      2:
        answer: "Horse"
        outcomes:
          - "Poseidon"
      3:
        answer: "Pig"
        outcomes:
          - "Demeter"
      4:
        answer: "Vulture"
        outcomes:
          - "Ares"
      5:
        answer: "Owl"
        outcomes:
          - "Athena"
      6:
        answer: "None of these"
        outcomes:
          - "Nike"
          - "Iris"
          - "Satyr"
  2:
    question: "In battle which position are you most likely to take?"
    answers:
      1:
        answer: "Defensive positions"
        outcomes:
          - "Apollo"
          - "Satyr"
      2:
        answer: "Frontline attack"
        outcomes:
          - "Ares"
          - "Zeus"
          - "Poseidon"
      3:
        answer: "Strategy planning"
        outcomes:
          - "Athena"
          - "Nike"
      4:
        answer: "Communications"
        outcomes:
          - "Iris"
  3:
    question: "What is your favourite element?"
    answers:
      1:
        answer: "Air"
        outcomes:
          - "Zeus"
          - "Iris"
          - "Athena"
          - "Nike"
      2:
        answer: "Earth"
        outcomes:
          - "Demeter"
          - "Satyr"
      3:
        answer: "Fire"
        outcomes:
          - "Poseidon"
          - "Dionysus"
      4:
        answer: "Water"
        outcomes:
          - "Ares"
          - "Apollo"
